### ISSUE TITLE
Site not scaling properly 

### ISSUE THREAD

**Issue by jailbreakerVC** [jailbreakerVC/websiteV2#1]
To reproduce: 
Open the project in different browsers, site does not scale to different screen sizes.

**Comment by abitsalihu** [comment]
Hey @jailbreakerVC, I checked the code, I can make your website responsive but I have to change a lot of your code!

**Comment by jailbreakerVC** [comment]
Hey! Appreciate it, Although I think I will just re-write the entire thing.

**Comment by abitsalihu** [comment]
@jailbreakerVC Oh okay, my suggestion would be trying to use more flexbox, and try to not use any position absolute as that will make the website not responsive at all. Have fun coding! :)

**Comment by jailbreakerVC** [comment]
For this I used figma and exported to HTML, now I will write code natively. Thanks.
